version: '3'
services:
    backend:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./:/var/www/html
        depends_on:
            - database

    database:
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend-laravel-api
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
